### ISSUE TITLE
Change to Membership module for Rome

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-landing#112]
## Background

In order to make it possible to change the authentication account of an actor in a given role, most modules will use a separate identifier for the actor, often called `ActorId` or something similar, and then have a separate mutable `AccountId` represent the current credential for authenticating this actor.

At the same time, we want to bind together all the different roles that an actor occupies on the platform at any given time, and historically, through the concept of membership. This means that we will in fact _require_ that any entrant into a role has some preestablished membership, and this may membership may at any time impose constraints on whether a membership is even allowed to enter a role at a given time, or whether the same type of role can be occupied more than once by a membership. For example, the same membership should arguably not be able to occupy multiple council seats.

## Problem

Currently, there is no principled approach for binding together a role with a membership. 

- The forum doesn't even use an internal identifier separate from accounts
- The council is totally isolated from membership.
- The storage role is bound to memberships, and the membership binding is held in the `Roles` module.
- The validators don't need a membership at all.

We are now introducing the idea of publishers and curators, and it's not clear how to move forward in a principled way. 

- **Where should the binding information be held?**
- **How is the check for admissibility of an account into a role made from the use case-specific module?**

### For Rome

In Rome we make changes to the `Membership` module which clearly indicate how to integrate membership with other roles, and start out with having the curator, publisher, council and forum use this. Validators and storage are left out for now, as changing those will have broader implications.

### Specifics

Firstly, for the time being its simplest to assume that there will only be a finite number of 

```Rust

// Configurable Id types
type RoleActorId;
type MemberId;

// Types
enum RoleType {
 ForumUser,
 Curator,
 CurationLead,
...
}

struct ActorInRole {
 role_type: RoleType,
 role_id: RoleActorId
}
 
struct Member {
 id: MemberId,
 
 // Account used to switch `signing_account`.
 // Can only be updated using existing `master_account`.
 master_account: AccountId,
 
 // Account used to do normal things like sign up to new roles with membership,
 // voting, etc.
 controller_account: AccountId,
 
 // Set of roles this member is an actor in.
 roles: BTreeMap<RoleType, Vec<RoleActorId>>
...
}

// State
membershipsById: Map MemberId => Member
membershipByActorInRole: Map ActorInRole => MemberId

// Public method

/* 
 * Returns true Iff 
 * (member exists) &&
 * Role specific policy allows this member to enter role, for example, 
 * a given type of role could possibly only be occupied at most once by the same member.
 * 
 * This is a utility method, most other use case module will not need to call this directly.
*/
fn can_register_role_on_member(signing_account: AccountId, role: RoleType) -> Result<(),'static str>;

/* ... */
fn can_unregister_role_on_member(role: RoleType, role_actor_id: RoleActorId) -> Result<(),'static str>;

/* 
 * Returns true Iff `can_register_role_on_member(signing_account, role, role_actor_id)`
 * 
 * When true is returned, the `roles` is updated for member.
*/
fn register_role_on_member(signing_account: AccountId, role: Role, role_actor_id: RoleActorId) -> -> Result<(),'static str>;

/* same for actually unregsitering ... blabnla nla */

```

A use case-specific module will call `can_register_role_on_member` and `register_role_on_member` when introducing a new actor with a given module actor id. Importantly, the module need not depend on the `Membership` module specifically and just needs some minimal configuration. E.g. if a module _N_ separate role types with names `ROLE1`,...,`ROLEN`, then you do

```Rust
trait Trait { 
 fn register_ROLE1_actor(account:AccountId, id: RoleActorId) -> bool;
 ...
 fn register_ROLEN_actor(account:AccountId, id: RoleActorId) -> bool;
}
```

The implementation can map these literal names to the underlying `RoleType` values, that way the caller module is insulated from dependency on the `Membership` module. This is in fact very natural functionality, even in very general-purpose modules, such as the forum, because even a general forum will want to be embeddable in a context where the runtime developer can control who can and cannot establish forum participation at any time.

## Note

- This way of organising the role to membership binding information will make it very easy for client applications to understand what a member is involved in. Currently, it would required detailed inspection of lots of different modules, which also would more easily break with changes to any one of those modules.

- In the future we may add more roles, even validators.

**Comment by bedeho** [comment]
Temporary note from meeting
- We will enforce unique role ids per type
- change name RoleActorId
- Drop approach with `register_ROLEN_actor` in favor of defining a new trait which is passed in mutiple times.

**Comment by bedeho** [comment]
Questions.

1. Doesn't there need to be a separate map in the state which uses the controller key of a member to recover the membership id? It appears this is required for sublinear lookup time of a member, based on an account, which is the way we are currently presuming that other modules will identify users.  Specifically in `can_register_role_on_member` and `register_role_on_member`.

2. I presume that when `signing_account` is passed in `can_register_role_on_member`, it is so that the membership module can use it to recover a member based on a match with the `controller_key`. If so, perhaps we should rename the variable name in the signature to `controller_key`? Same in `register_role_on_member`.

3. Should `can_unregister_role_on_member` just take a `ActorInRole` for clarity?

4. I am trying to add support for updating the equivalent of the role account, but for a specific working group. I don't think it makes sense to require the role account itself to sign for this, for example, if the key has been lost. Instead, it makes sense to be able to switch out the role key for an actor in this working group by using the controller key of the membership. To support this, I would like to have a call of the form

`fn key_can_sign_for_role(signing_account: AccountId, actor_in_role: ActorInRole) -> bool;`

**Comment by mnaamani** [comment]
1. Yes - in the implementation I added it
2. Yes - in the implementation I renamed the parameter to controller_account
3. It can, however I had to introduce a `RoleId` separate from the `enum RoleType`.  I'm keeping `ActorInRole` as in internal type not be exposed to the
