### ISSUE TITLE
Possible further amendments to version store in Rome

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-landing#136]
1) factor out `can_only_be_ref_by` and give i a better name
informed by very clear semantics: If (x,y) is in set, then a property value with index `x` in class can be referenced by an entity of this class _only_ if it is the same owner.

2) add support for external ids in version store, so that channels (which will now be outside) can be integrity checked.

3) internal class references are versioned. NB: external class referenced have no versioning.

4) add `entities_can_add_schema_support_only_for: Set<schemaids>` to `ClassPermissions`, which controls the set of schemas under which one can currently add schema support to entities. `admins` can mutate this only.

5) Change name to `InternalClassPermissions` ?

6) Complete the ongoing refactorings which @mokhtar is doing, which includes removing `AccountId` as a prinicpal type.

7) Version tool of @martin @alex needs to
   - accept particpantId as argument, and be able load keys for this role locally
   - update existing schema format to support new version internal class reference property
   - update existing schema format to support `can_only_be_ref_by` information into class creation
   - update existing schema format to support external class reference property
   - introduce a second file format for specifying the `ClassPermission` fields, for the different classes to be created. It should be separate in order to allow the pure version store format social discussion which does not include irrelevant permissions information.

8) Make runtime aware of vector containers

9) Add nonce for updating property values to avoid race conditions, in particular on vectors

**Comment by bwhm** [comment]
Joystream/substrate-versioned-store-permissions-module#2
