### ISSUE TITLE
Make faucet reliable.

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-landing#204]
We frequently get users coming to our TG channel due to some sort of failure in our testnet faucet. Its reasonable to assume that many more will experience these failures, and not even bother to come ask for tokens manually. This is bad for onboarding new community members and testnet engagement. If this faucet is to be used for Constantiniople, then I think we need to try to make it more reliable.

**Comment by bedeho** [comment]
It was mentioned that this may be caused by the faucet being very frequently depleted due to Sybill attacks. If that is the case, we can at least

a) Have a proper error message that warns them that Faucet is empty, perhaps even before they try anything, and directs them to Telegram.

b) Perhaps alert us internally that its empty when it runs out, so we can get ahead of it in some way.

**Comment by bwhm** [comment]
Faucet will be trough telegram.
