### ISSUE TITLE
Design Proposal: Media System

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-landing#74]
# Design Proposal: Media System aka Content Directory

# Content Directory
The core goal is to make it possible to have a very flexible and useful system which does not require runtime upgrades or migrations, as these are both risky and require a lot of coordination in council or among voters, making it hard to do frequent changes.

## Naming problem

The name might be bad, I don't think its just for "content", as stuff you can play or watch, it can have much more stuff, like profiles, people, places, events, etc. But not sure what to call it yet.

## Design Goal

1. Easily add new types of information without runtime upgrades, for example people, place, media, events, locations etc.

2. The same information can come in multiple versions, to avoid the need for instant simultanous migrations of all information. For example there may be a place "Oslo", which comes in versions {7,8,9}, while "Kiev" may come in versions {10}. 

3. Easily identify the set of all entities of a given type, irrespective of versioning. This is very useful for end user applications. For example for the place type, we easily want to know that there are two basic places "Oslo" and "Kiev".

4. A flexible permission system to restrict who can add informaiton or update a field.

5. Basic integrity checking of field values when adding or updating.

## Background

To provide a rich media experience that caters for different modes and levels of access to content, the platform must address how to discover, access, consume, pay for and interact with media and publishers of that media.
As such the platform is composed of an infrastructure layer supported by a rich media system.
While the infrastructure layer, made up of the storage and distribution system, and in the future the live streaming system, are responsible for storing and distributing digital assets in a reliable, performant and cost effective way, the media system is a complementary data store which holds information such as:

- metadata
- categories
- people (artists, show hosts, actors, narrators, directors..)
- publishers (original content creators on the platform)
- organization of different media types
  - video
  - podcasts
  - feature films
- playlists
- ownership
- license
- attribution
- monetization
- links to related external social media (comments, likes, view counts)

## Primary Goals

- Extremely flexible: its very easy to safely change what is represented there, in order to guide offchain policies of how to interact with media in the system.
- Can represent both support assets in storage & distribution, as well as offsite HTTP Resources
- No need for runtime upgrades or migrations except when adding support for new "external references" (data in other modules)

## Design Overview
The media system will be built on top of an on-chain general purpose versioned object database.
Before an object in the database can be created, a class, schema and entity must first be created.
Below is a high level explanation of these concepts.

### Class
A `Class` represents a "concept" that we wish to model in the database. There can be many instances of a Class, called entities. A class is part of a class group. This group is for partitioning purposes. Classes in a group do not necessarily share a common theme or trait. A Class has a unique global identifier in the database.

Think: "Planet"

### Entity
An `Entity` represents a singular existence of a particular Class, but does not itself hold any data.
It has a unique global identifier in the database and is associated with a single class.

Think: "Earth"

### Schema
A schema is a particular way a class can be represented, as an ordered collection of properties.
A schema is immutable. To allow adding new ways to represent a class, multiple versions of schemas can be created for a class. A specific schema is semantically versioned and can only be associated with a single class.

Think: Planet.v0 ["Mass", "Distance From Sun", "Number Of Moons"]

### Object
An object is the collection of the property values conforming to a schema version for a specific entity.
For every entity there can only be one object for every schema version.
An object can be thought of as a singleton instance of a schema.

Think: Earth.v0 ["5.98x10^24 kilograms", "146 million km", "1"]

## Permission system:
To maintain integrity and high quality a permissions system is necessary.
The following actions in the database are permissioned. An external module which implements the `PermissionChecker` (configured at runtime construction) will handle granting authorization.

`Create Class Group`
`Create Class`
`Create Schema`
`Create Entity`
`Create Object`
`Update Object`

This separation of concerns will allow different runtimes to have different levels of granularity of permission for the database. To aid in reuse of the database in the same runtime, it can be partitioned by use of Class Groups.

## External Properties - Referencing information exogenous of the database
Object properties can be of various data types to represent strings and numbers. Object properties can also be references to other entities (Internal type) or references to arbitrary data elsewhere in the system (External type). The latter is achieved by introducing the concept of a type checker. External types are identified by a tuple of a moduleId and a propertyId. The type checker acts as a proxy to invoke a check and validate method on the module that holds the information being referenced.

### Proposed Classes for first version of media system in Rome testnet
A minimal set of actual concepts/classes to represent, and how to integrate them with rest of system.
make available all content from http://publicdomainmovies.net/

**Comment by mnaamani** [comment]
# Substrate Versioned Object Database

## Types & Constants

```Rust
/// Constants - make compile time parameters
const MAX_NAME_LENGTH: u32 = ..;
const MAX_DESCRIPTION_LENGTH: u32 = ..;
type Description: [u8, MAX_DESCRIPTION_LENGTH];
type Name: [u8, MAX_NAME_LENGTH];

trait Trait {
  type ClassId;
  type EntityId;
  type SchemaId;
  type ObjectId;
  type ClassGroupId;

  type ExternalModuleId;
  type ExternalPropertyType; // numerical id
  type ExternalPropertyId;
  type ExternalProperty; // (ExternalModuleId, ExternalPropertyId)
  type PermissionChecker: PermissionChecker;
  type ExternalPropertyChecker: ExternalPropertyChecker;
}

struct SemanticVersion {
  major_version: u16,
  minor_version: u16
}

// A Class Group is a top level logical grouping of Classes. It allows for segmenting the database and assigning different sudo accounts for different groups. A class group sudo can only create new classes under their group, and entities of classes in the same group.

// eg. Planet = Class {
//  name: 'Planet',
//  description: 'A body in space that orbits a star'
// }
struct Class<T: Trait> {
  group: ClassGroupId,  // a way to namespace/segment the database for different uses (different top level sudo accounts)
  name: Name,
  description: Description
}

// An instance of an 'Entity' "is a" 'Class'
// ie. Earth 'is a' Planet
// eg. {
//  class: <Planet>,
//  name: "Earth"
//}
struct Entity<T: Trait> {
  class: T::ClassId,
  name: Name
}

// A schema defines one way to describe the properties of an instance of Entity
struct Schema<T: Trait> {
  class: ClassId,
  version: SemanticVersion,
  properties: Vec<Property>,
  description: Description
}

struct Object<T: Trait> {
  schema: T::SchemaId,
  entity: T::EntityId,
  values: Vec<PropertyValue>
}


type PropertyValues: Vec<PropertyValue>;
// A possible change to a new column value, or no change.
type PropertyValueChange: Option<PropertyValue>;
type PropertyValueChanges: Vec<PropertyValueChange>;

trait PermissionChecker {
  pub fn can_create_class(origin: AccountId, group: ClassGroupId) -> bool;
  pub fn can_create_schema(origin: AccountId, classId: ClassId, properties: &Vec<Property>) -> bool;
  pub fn can_create_entity(origin: AccountId, classId: ClassId);
  pub fn can_create_object(origin: AccountId, entityId: EntityId, schema: SchemaId, values: &PropertyValues) -> bool;
  pub fn can_update_object(origin: AccountId, objectId: ObjectId, valueChanges: &PropertyValueChanges) -> bool;
}

trait ExternalPropertyChecker {
  type checkValue: fn (propertyId: ExternalProperty, value: ExternalPropertyType) -> bool;
  // used when addin a new schema, property must be of known type
  type checkPropertyIdExists: fn (propertyId: ExternalProperty) -> bool;
}

struct Property {
  data_type: PropertyDataType,
  optional: bool,
  name: Name,
  description: Description,
}

enum PropertyDataType {
  External(ExternalProperty),
  Internal(ClassId),
  unsigned_integer_64,
  signed_integer_64,
  float64,
  varchar(u32),
  boolean
}

enum PropertyValue {
  External(ExternalPropertyType),
  Internal(EntityId),
  unsinged_integer_64(u64),
  signed_integer_64(i64),
  float64(f64)
  boolean(bool),
  varchar(Vec<u8>),
  none
}

```

## State
```Rust
classById: map ClassId => Class
entityById: map EntityId => Entity
schemaById: map SchemaId => Schema

objectById: map ObjectId => Object
// map to track objects created for an entity, to ensure single object inserted for a schema
objectIdForEntityAndSchema: map (EntityId, SchemaId) => ObjectId
```

**Comment by siman** [comment]
@mnaamani it would help to have an example of how would express Video and Playlist using the structs you described: Class, Class Group, Entity, Schema, Object, Property, etc.

**Comment by siman** [comment]
Did you consider using `required` instead of `optional`?
It's more intuitive to check a `required` field rather than `!optional` for the things that should be present on an object. 
```rust
struct Property {
  data_type: PropertyDataType,
  optional: bool,
  name: Name,
  description: Description,
}
```

**Comment by mnaamani** [comment]
> @mnaamani it would help to have an example of how would you express let's say Video and Playlist using the structs you described above: Class, Class Group, Entity, Schema, Object, Property, etc.

For ClassGroup just assume all classes are in the same group `0` that will represent the content directory.

Because we haven't included an array for property types, we will need three classes
Video, PlayList and PlayListEntry (The video class is not strictly required the playlist entry could directly reference an external dataobject)

key => value in various state maps

```
0 => Class {
   group: 0,
   name: "Video",
   description: "A Video from the data directory"
}

1 => Class {
  group: 0,
  name: "PlayList",
  description: "List of Videos"
}

2 => Class {
   group: 0,
   name: "PlayListEntry",
   description: "An entry in a playlist"
}
```

A simple schema for the Video class that just references a dataobject from the data directory.
```
0 => Schema {
   class: 0, // the Video classId
   version: SemanticVersion {major: 1,  minor: 0},
   description: "Video from data directory",
   properties: vec![
       Property {
           data_type: PropertyDataType::External(("DataDirectory", 5)) // this mapping will be interpreted by another "type checker" module, we infer that it means dataobjectid in dataobjectfamily 5
          optional: false,
          description: "Data Object Id"
      },
      Property {
           data_type: PropertyDataType::varchar(256),
           description: "Title"
       }
    ]
}
```

A simple schema for the PlayList class:
```
1 => Schema {
    class: 1,
    version: ...,
    properties: vec![
        Property: PropertyDataType::varchar(32),
        optional: false,
        description: "Playlist Title"
   ]
}
```

A simple schema for the PlayListEntry class:
```
2 => Schema {
    class: 2 // PlaylistEntry classId,
    properties: vec![
       Property {
           data_type: PropertyDataType::Internal(1), // PlayList classId
           optional: false,
       },
       Property {
          data_type: PropertyDataType::Internal(0), // Video classId
          optional: false,
       },
    ])
}
```

Lets create a few videos

```
0 => Entity {
    class: 0, // Video
    name: "Video1"
}
1 => Entity {
    class: 0, // Video
    name: "Video2"
}
2 => Entity {
    class: 0, // Video
    name: "Video3"
}

0 => Object {
   entity: 0,
   schema: 0,
   values: vec![
       PropertyValue::External(245), // dataobjectid 245
       PropertyValue::varchar("Dataobjectid 245")
   ]
}
1 => Object {
   entity: 1,
   schema: 0,
   values: vec![
       PropertyValue::External(123), // dataobjectid 123
       PropertyValue::varchar("Dataobjectid 123")
   ]
}
2 => Object {
   entity: 2,
   schema: 0,
   values: vec![
       PropertyValue::External(777), // dataobjectid 777
       PropertyValue::varchar("Dataobjectid 777")
   ]
}
```

Then create two playlists:
```
3 => Entity {
   class: 1, // playlist classid
   schema: 1, // playlist schema id
   name: "Home Videos"
}

4 => Entity {
   class: 1,
   schema: 1,
   name "Documentaries"
}

3 => Object {
   schema: 1,
   entity: 3
   values: vec![PropertyValue::varchar(bytes!["My Home videos Playlist"])]
}

4 => Object {
    schema: 1,
    entity: 4,
    values: vec![PropertyValue::varchar(bytes!["My Documentaries Playlist"])]
}
```

Finally populate the playlists by creating playlist entries:
```
5 => Entity {
   class: 2,
   schema: 2,
   name: "entry1"
}

6 => Entity {
   class: 2,
   schema: 2,
   name: "entry2"
}

7 => Entity {
   class: 2,
   schema: 2,
   name: "entry3"
}

5 => Object {
   schema: 2,
   entity: 5,
   values: vec![
       PropertyValue::Internal(4), // documentaries playlist entityid
       PropertyValue::Internal(0) // first video entity id
}

6 => Object {
   schema: 2,
   entity: 6,
   values: vec![
       PropertyValue::Internal(4), // documentaries playlist entityid
       PropertyValue::Internal(1) // second video entity id
}

7 => Object {
   schema: 2,
   entity: 7,
   values: vec![
       PropertyValue::Internal(5), // home videos playlist entityid
       PropertyValue::Internal(2) // third video entity id
}
```

**Comment by mnaamani** [comment]
There are some limitations in the example for the Playlist. If we don't support deleting objects and by not having an Array property type, removing entries from the playlist is awkward. To do that it would mean updating the playlist entityid on the entry object to point to a "null" playlist.

Should we consider adding an Array type and/or allow deleting objects?

**Comment by mnaamani** [comment]
Diagram to illustrate relationship between Classes, Entities, Schemas and Objects:
![Screen Shot 2019-07-17 at 3 10 36 PM](https://user-images.githubusercontent.com/1621012/61374505-28daaa00-a8a5-11e9-98f6-f0dd0e55dcf4.png)

**Comment by mnaamani** [comment]
@siman raised an important point in the proposed design when it comes to duplication of data. Lets say a new schema only wants to introduce a new property and all other properties are identical. This would mean new objects created under the new schema would have to duplicate values from other objects. At the cost of state storage space this allows easy read operations to get all the object properties, and doesn't introduce any coupling between objects of the same entity. This makes it possible to "prune" the database by removing objects that are instances of old schemas. (If it is desirable)

If we wish to save on storage space under with the current model we could introduce a new `PropertyDataType`:
`BackPointer(ObjectId, PropertyIndex)` which points at a property in an existing object.

This adds some complexity in the UI when it comes to updating an object's properties but is workable.
To make sure the UI doesn't need to support a huge range of schemas we can limit the reference to the object to be of the same major version number.

**Comment by bedeho** [comment]
I think there are two separate issues

1. State storage
2. Schema property linking

I am not sure how concerned we should be about 1, some calculations could be in order ( looking at spreadsheet master @bwhm ).

I am more concerned about 2, as we may be not reflecting all relevant versioning information in our design, which is that schema fields are often the same "thing" across versions. I don't have a super great use case for incorporating this information, but is it a given that modeling it should imply that there can only be one shared value? I am not sure. 


You are modeling a fix where a schema talks about an object, I am not sure that is right, is that a mistake? Shouldn't one schema of version (t+1) talk about a property index in a version t schema? Alternatively, if one wants to decouple from the immediately preceding version, one could just talk about an arbitrary schema version. This latter approach could be a bit nicer, as it avoids long chains of version dereferencing to find the true value to use.

**Comment by mnaamani** [comment]
With regards to the model yes semantically it makes more sense to think of referring to a previous schema rather than an object (but in the overall model there will be enforcement of one instance of an object per entity for each schema so it was just a shortcut to point at the data directly and reduce one lookup).  The model itself does allow one to point at an arbitrary schema version because we are providing the schemaid not the version directly. I think we can and should limit the length of the chain of version dereferencing to length 1 by following two rules:
- pointer can only be to a property in a schema of the same major version number
- pointer can not be to a property that is of type BackPointer
In this way we also reflect that for the same major version number the property fields across for all minor versions is the same "thing"

If this model is good enough then it solves the second issue and we get the first issue solved for free?

**Comment by mnaamani** [comment]
Following discussion today with @alex and @bedeho here is a simpler representation that eliminates the need to have a separate Object struct, eliminates duplication of values (for the same property of an entity in newer schemas), also allows us to reuse a defined property in many schemas (reducing duplication of property types)

### Types 
```Rust
type Description: [u8, MAX_DESCRIPTION_LENGTH];
type Name: [u8, MAX_NAME_LENGTH];

type ClassId = u64;
type EntityId = u64;
type SchemaId = u64;
type PropertyId = u64;

type Version = u16;

struct Class<T: Trait> {
  name: Name,
  description: Description
}

struct Entity<T: Trait> {
  class: T::ClassId, // entity is an instance of this class
  name: Name
}

// A schema defines what properties describe an entity
struct Schema<T: Trait> {
  class: ClassId, // what class it describes
  version: Version,
  properties: Vec<PropertyId> // set of property Ids - order is not important
}

struct Property {
  data_type: PropertyDataType,
  optional: bool,
  name: Name,
  description: Description,
}

enum PropertyDataType {
  External(ExternalProperty),
  Internal(ClassId),
  unsigned_integer_64,
  signed_integer_64,
  float64,
  varchar(u32),
  boolean
}

enum PropertyValue {
  External(ExternalPropertyType),
  Internal(EntityId),
  unsinged_integer_64(u64),
  signed_integer_64(i64),
  float64(f64)
  boolean(bool),
  varchar(Vec<u8>),
  none
}

```

### State
```Rust

map ClassById : ClassId => Class
map SchemaById: SchemaId => Schema
map EntityById: EntityId => Entity
// when updating entity we can keep track of what version of schema it is available in
map EntityVersions : EntityId => Vec<SchemaId>

// Property constraint, type, description. A propertyId can be used in a multitude of unrelated schemas
// and will save on duplication
map PropertyById : PropertyId => Property
// The property value for a specific entity
map EntityPropertyValue : (EntityId, PropertyId) => PropertyValue

// Reading an entity's property values goes as follows:
// Given an entity id we get all schema ids for that Entity from `EntityVersions`
// Select which schema version we are interested in
// Get the property Ids of that schema "Schema.properties" from SchemaById
// ready key (EntityId, PropertyId) from EntityPropertyValue
```

**Comment by mnaamani** [comment]
This diagram illustrates how construct the runtime to have multiple modules be sources of external properties.

![Screen Shot 2019-07-22 at 4 32 23 PM](https://user-images.githubusercontent.com/1621012/61636619-a552fb80-ac9e-11e9-9395-f7e902f267a3.png)

With this construction any number of modules can be configured (by setting the Providers associated type). The trick is to always pass the modules as a tuple of either (X, ) or (X, Y). Example with multiple modules
modules: A.             Providers = (A, )
modules: A, B.         Providers = (A, B)
modules: A, B, C.     Providers = ((A,B), C)
modules: A, B, C, D. Providers = ((A, B), (C,D))

```Rust
trait ExternalPropertyProvider {
  fn hasProperty(domainId, propertyId) -> bool;
  fn validPropertyValue(propertyId, value) -> bool;
}

impl<X: ExternalPropertyProvider> ExternalPropertyProvider for (X, ) {
    fn hasProperty(domainId, propertyId) -> bool {
        X::hasProperty(domainId, propertyId)
    }
   fn validPropertyValue(domainId, propertyId, value) -> bool {
       X::validPropertyValue(domainId, propertyId, value)
   }
}

impl<X: ExternalPropertyProvider, Y: ExternalPropertyProvider> ExternalPropertyProvider for (X, Y) {
    fn hasProperty(domainId, propertyId) -> bool {
         X::hasProperty(domainId, propertyId) || Y::hasProperty(domainId, propertyId)
    }
   fn validPropertyValue(domainId, propertyId, value) -> bool {
       X::validPropertyValue(domainId, propertyId, value) || Y::validPropertyValue(domainId, propertyId, value)
   }
}
```

**Comment by bedeho** [comment]
Yet another variation I am writing down for discussion purposes. It mixes two ideas

1. Properties are tied to Classes, and Values are tied to Entities.
2. Absorb types as Vec<T> in one too many relationships when there is not going to be a very large number of values, say < 20. Just because it's practical, and avoids having to have so many ids around. But really, just sugar.

### Types 
```Rust

struct Class<T: Trait> {
  name: Name,
  description: Description,

  // For Person, think "height", "weight", etc.
  // Unlikely to be more than roughly 20ish, often less.
  properties: Vec<Property>,

  // All scehmas that are available for this class, think v0.0 Person, v.1.0 Person, etc.
  class_schemas: Vec<ClassSchema>
}

struct Entity<T: Trait> {
  class: T::ClassId, // entity is an instance of this class

  // What schemas under which this entity of a class is available, think
  // v.2.0 Person schema for John , v3.0 Person schema for John
  // Unlikely to be more than roughly 20ish, assuming schemas for a given class eventually stableize, or that very old schema are eventually removed.
  schemas: Vec<u32>, // indexes of schema in corresponding class

  // Values for properties on class that are used by some schema used by this entity!
  // Length is no more than Class.properties.
  values: Vec<(u32, PropertyValue)>, // Index is into properties vector of class. Fix anonymous type later.
  name: Name
}

// A schema defines what properties describe an entity
struct ClassSchema<T: Trait> {
  version: Version,
  properties: Vec<uint> // indexes into properties vector for the corresponding class
}

struct Property {
  data_type: PropertyDataType,
  optional: bool,
  name: Name,
  description: Description,
}

enum PropertyDataType {
  External(ExternalProperty),
  Internal(ClassId),
  unsigned_integer_64,
  signed_integer_64,
  float64,
  varchar(u32),
  boolean
}

enum PropertyValue {
  External(ExternalPropertyType),
  Internal(EntityId),
  unsinged_integer_64(u64),
  signed_integer_64(i64),
  float64(f64)
  boolean(bool),
  varchar(Vec<u8>),
  none
}

```

### State
```Rust
map ClassById : ClassId => Class
map EntityById: EntityId => Entity
```

**Comment by mnaamani** [comment]
### Methods Internal only
To make the module implement the "protected module" pattern we only need to implement internal methods which will be called from a proxy module. See the [ACM proposal](https://github.com/Joystream/joystream/issues/84) for details.

```
create_class(name, description, properties: Vec<Property>, Vec<ClassSchema>) -> Result<ClassId, Error>
add_class_property(classId, property) -> Result<u32, Error>
add_class_schema(classId: ClassId, schema: ClassSchema) -> Result<Error>

create_entity(name, classId, schemaIdices: Vec<u32>, propertyValues: Vec<(u32, PropertyValue)>) -> Result<EntityId, Error>
update_entity(entityId, schemaIdices: Vec<u32>, propertyValues: Vec<(u32, PropertyValue)>) -> Result<Error>
delete_entity(entityId) -> Result<Error>
```

**Comment by mnaamani** [comment]
One way to model the permissions on the content directory using the ACM proposal:
```
  ACM root
   |
   |--content-directory-(0)
      |--class-(1)
      |   |--schema-(2)
      |   |   |---property-(3)
      |   |   |---property-(4)
      |   |--entities-(5)
      |       |--entity-(6)
      |       |--entity-(7)
      |--class-(8)
```

With a simple ACL below, we can have a group of admins have full permission to create classes, new schemas and entities in the content directory. Members (an external group) can create entities of one class. Member that creates a new entity will be set as its owner and can update it.

```
NodeId      Acl 
----------------------------------------------------------
0              { Allow, ContentDirAdminGroup, All }
5              { Allow, PlatformMembersExGroup, AddChild }
```

**Comment by mnaamani** [comment]
We are dropping the ACM model, instead a specific permissions module for the content directory is here https://github.com/Joystream/joystream/issues/92

**Comment by blrhc** [comment]
@bedeho, if "Content Directory" isn't a very good name for what you're working on, have you considered:

- Component Index?
- Element Index?
- Constituent Index?

You might also consider replacing "index" with: _list, listing, register, registry or catalogue_ if those sound better.

Just my (possibly unhelpful) two cents!

**Comment by bedeho** [comment]
I think we have just stuck with content directory for now :D
